import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Personal Savings Goal Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <h1>Personal Savings Goal Tracker</h1>
        {/* home page of the website */}
        <p>Welcome to the Personal Savings Goal Tracker!</p>
        <p>Track your savings goals and amounts with ease.</p>
        <p>Get started by creating a new account or logging in.</p>
      </main>
    </>
  );
}
