import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Personal Savings Goal Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <h1>Personal Savings Goal Tracker</h1>
        <ul>
          <li>
            <a href="/add-goal">Add Goal</a>
          </li>
          <li>
            <a href="/goals">View Goals</a>
          </li>
          <li>
            <a href="/login">Login</a>
          </li>
          <li>
            <a href="/signup/">Signup</a>
          </li>
        </ul>
      </main>
    </>
  );
}
